### ISSUE TITLE
Library Unread API does not return 'content: []' in payload when empty

### ISSUE THREAD

**Issue by Ligerx** [TachiWeb/TachiWeb-Server#15] opened 2018-06-04 21:16 UTC
The new Unread api returns {"success":true} when the library is empty.
I am expecting {"success":true,"content":[]} which is the same as what Library returns when empty.

**Comment by null-dev** [comment] 2018-06-04 21:22
Actually a duplicate of #14

**Closed by null-dev** 2018-06-04 21:22 UTC

**Comment by null-dev** [comment] 2018-06-16 19:54
@Ligerx My bad, I messed up the API endpoint, it's actually: `/api/library?jw=$.success&jw=$.content.*.unread&jw=$.content.*.id&jw=$.content`
