### ISSUE TITLE
Category ids are not incremented correctly

### ISSUE THREAD

**Issue by Ligerx** [TachiWeb/TachiWeb-Server#43] opened 2019-08-03 05:35 UTC
When you create a category, it creates a new one with id of the largest non-deleted id + 1. However, this is incorrect behavior because it's possible to create a new category with an old id and that old ids' corresponding manga.

*example*
1. Create a category
2. Add manga to that category
3. Delete that category
4. Create a new category (name doesn't matter)
5. Observe that the id is the same as the first category and it 'remembers' your manga in this category

I believe expected behavior is that category ids do not get reset. They continue to increment even if categories are deleted.

**Comment by null-dev** [comment] 2019-08-23 05:39
Fixed in https://github.com/TachiWeb/TachiWeb-Server/commit/102ca6230358eb0a505948d15d49765f5c360dc6

The category id increment behavior was actually correct. The category manga being remembered was definitely not intended behavior.

This issue occurred because the cleanup calls were not being run after stuff was deleted in the database. This was a pretty critical issue, and it probably caused a ton of other bugs... Excellent find!

**Closed as completed by null-dev** 2019-08-23 05:39 UTC
